language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Reverse proxy
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy pta201/reverseproxy:latest
  # Frontend
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend pta201/udagram-frontend:latest
  # Users microservice
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user pta201/udagram-api-user:latest
  # Feed microservice
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed pta201/udagram-api-feed:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push  pta201/reverseproxy:latest
  - docker push  pta201/udagram-frontend:latest
  - docker push  pta201/udagram-api-user:latest
  - docker push  pta201/udagram-api-feed:latest