apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQldTN1lRV2dVUnd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBME1UUXhNakEwTWpKYUZ3MHpOREEwTVRJeE1qQTVNakphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM0K0JaQTBXQitJbFRadkpYdjVKZWxKd0xla3VrT1d4eW9oajRMczNvbHpmMW5BYTl5dk85dUxjeE8KZDBQM0ZkQ0VUREJScTF4d2NiNFhVeHNGYVV4TGkzQXNLYU1IbkNwUlBBZ3dOUzVPRCtRTmxCL2NNS0J2M3lZYwpiQ3pQZ2Iwa1RBb3hiZWVBMjZtVFZ6WjFFWGdvRXh2UnQxL0lGUkNCT3dNdkFsbkx3OTU3TmVNT1dEUU1vbTRmClhNejRtckhiZGZ1R2NwY1ZGYU9SQ2hwK2NlMGFxd2cvbXowUVJTdk91SExCR1VPMk1WNTZZWWw5TXllR2M1VkoKbkpXU0xOU1k2NVRjZWpsaWN0dnNOMXpqQnVCZ0tqOG9OWHZpL0o0T2htUzhkbkM1aTN2YVJwN01tMGphZGpOQgoyRHJoTjg1dXlZQm0va0Z1ZkprS0VhMnR1UjBMQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTM2FnK0pHOG5seVRwd05PQUI4U3gxaU0zM3FqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUQ1ems0a1dEeAo0T1pmbjZVVkZoOVliZWkvTmFuMEZaLzkzUUUreVpQMHd3L1dzSURzOS8wWWY3bFZqTGJONnVpdXF3TVREMTZLClViKzZSQm1kQTRqc3dPRWZqZkpYalZueXAwS0hLL3lvY1JrVWFMVkdaZCs4ejdYNmc0Z1QvVFplZWllanliQXQKNlBhZDAxQVdvT3pVcU5QaFVOR3Y4MG9pOU4yMGRoUWRxdG5hZGVMdnNrZzlJU1M3N0lIUVlkK0RLMkU4QUVkbAp3ZHJDdlQrZnpmN3h3WTYrNUlSbXFpNFdUMXJWd0JySEtyY0FvWWZmN2Q4eGRSem1mQXo3a1YrTS81dGZUTHdYCjV6a085ZEk1OVgzN3JNek12MzkzaE5NRnNXdEd6ZC8rQk1XcHNpYk1LR3g1NDNDNTQvUWRuSzFoT1RYR0o4S1UKdnFHM3RNckFveEpKCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8A0F622E5E70CC4FA21376EAE4C4B863.gr7.us-east-1.eks.amazonaws.com
  name: project-3-eks
contexts:
- context:
    cluster:  <cluster-name>
    user:  <cluster-name-user>
  name:  <cluster-name>
current-context:  <cluster-name>
kind: Config
preferences: {}
users:
- name:  <cluster-name-user>
  user:
    token: <secret-token-here>